# Copyright 2016 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""adding external network database models

Revision ID: d00a21c75615
Revises: 0e66c5227a8a
Create Date: 2016-04-23 17:08:18.649466

"""

# revision identifiers, used by Alembic.
revision = 'd00a21c75615'
down_revision = '0e66c5227a8a'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extnodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('extsegments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('types_supported', sa.String(length=36), nullable=True),
    sa.Column('ids_pool', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('extnodeints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=36), nullable=True),
    sa.Column('extnode_id', sa.String(length=36), nullable=True),
    sa.Column('extsegment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['extnode_id'], ['extnodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extsegment_id'], ['extsegments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('extinterfaces',
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('network_id', sa.String(length=36), nullable=True),
    sa.Column('extnodeint_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['extnodeint_id'], ['extnodeints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_extinterfaces_tenant_id'), 'extinterfaces', ['tenant_id'], unique=False)
    op.create_table('extlinks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('network_id', sa.String(length=36), nullable=True),
    sa.Column('overlay_id', sa.String(length=36), nullable=True),
    sa.Column('extsegment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['extsegment_id'], ['extsegments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('extconnections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=36), nullable=True),
    sa.Column('extnodeint1_id', sa.String(length=36), nullable=True),
    sa.Column('extnodeint2_id', sa.String(length=36), nullable=True),
    sa.Column('extlink_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['extlink_id'], ['extlinks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extnodeint1_id'], ['extnodeints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extnodeint2_id'], ['extnodeints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
